project_id = "kplfjrjibjptigvfgdvy"

[functions.webauthn-register-start]
verify_jwt = false

[functions.webauthn-register-finish]
verify_jwt = false

[functions.webauthn-auth-start]
verify_jwt = false

[functions.webauthn-auth-finish]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.save-game]
verify_jwt = false

[functions.load-game]
verify_jwt = false
